### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
@mlocati Found misspellings in code and comments.

### CODE REVIEW

**Comment by mlocati** [comment]
Have you really read all the code??? Wow!

**Comment by szepeviktor** [comment]
👉🏻 https://github.com/crate-ci/typos

**Comment by mlocati** [comment]
> Are code readers banned here? 🙃

Absolutely welcome!

> 👉🏻 https://github.com/crate-ci/typos

Nice!

**Comment by szepeviktor** [comment]
`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "docs/data/",
    "docs/fonts/vendor/",
    "docs/css/",
    "docs/js/",
]
ignore-hidden = false

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
```

**Pull request merged**
